### ISSUE TITLE
Get Primers online somewhere

### ISSUE THREAD

**Issue by rufuspollock** [artearthtech/primers#1]
Two parts:

* [x] Get a domain up
* [x] Put html + PDF versions of this stuff on that domain (a mini-website)

### Domain

Suggest a subdomain of artearthtech.com e.g. `research.aet.com` or even just `primers.artearthtech.com`.

I can get domain set up to point to github pages very easily.

### Hosting Site

Suggest we make a small github pages site and publish the stuff in (?)

*Comments welcome on this*

**Comment by Stiivi** [comment]
+1 for the `primers.*` domain.

> Suggest we make a small github pages site and publish the stuff in (?)

If we keep/check-in the generated output in the `docs` directory, it is [github-able](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

**Comment by Stiivi** [comment]
Generated [here](https://artearthtech.github.io/primers/index.html). Next step: [setup a custom domain](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)

**Comment by rufuspollock** [comment]
@Stiivi i've set up CNAME in the DNS. Just need to add a `CNAME` file to the repo now and it should work.

**Comment by Stiivi** [comment]
Pushed the CNAME file.

**Comment by rufuspollock** [comment]
FIXED. See http://primers.artearthtech.com/
